---
title: "Plateau-Mont-Royal"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Plateau-Mont-Royal}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  warning = FALSE, message = FALSE
)
```

```{r setup}
library(devtools)
load_all()

library(ggplot2)
library(dplyr)
library(sf)
```

Ce document décrit l'utilisation de `TreeZilience` pour l'arrondissement du Plateau Mont-Royal, depuis l'importation des données brutes d'inventaire jusqu'à la recommandation finale d'une liste d'arbre à planter. 

# Données 

Pour cet exemple, le chargement des données se fait directement grâce à la fonction `data()`. 

```{r data}
data(plateau) # délimitation de la zone d'étude 
data(plateau_inventory) # inventaire des arbres du plateau
#help(plateau_inventory) # description du jeu de donnée
```

```{r dataplot, echo = FALSE, fig.width=7}
ggplot() + 
geom_sf(data = sf::st_geometry(plateau)) + 
geom_sf(data = plateau_inventory, size = 0.1) +
theme_bw()
```

# Optimisation 

```{r opt}
optimize_results <- optimize_diversity(plateau, plateau_inventory, make_grid=TRUE, grid_dimension=250, add_trees="Default", n_add_trees=100, verbose = FALSE)
```

```{r optfr}
optimize_results$`Functional groups current` %>% head
```

```{r optsum}
optimize_results$`Optimisation summary` %>% head
```

```{r optfrp}
optimize_results$`Functional groups to plant` %>% head
```

```{r plotopt, echo = FALSE, fig.width=7}
plot(optimize_results$`Optimisation shapefile`['fdv_optimised'], main="Functional diversity optimized")
```



